version: "2.0"

services:
  consul:
    image: consul:latest
    ports:
      - 8400:8400
      - 8500:8500
      - 54:8600/udp
  consul-integration-demo:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - consul
    links:
      - consul:consul #add "127.0.0.1 consul" without quotes in /etc/hosts file
